version: '3.7'

services:
  spring:
    image: 'tada-spring:v0.1'
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    volumes:
      - ./src:/usr/src/app/src
